name = "blogroll"
account_id = "0de7ad47f547afcaca7575c5c24ad560"
workers_dev = true
compatibility_date = "2026-08-22"
# route = "blogroll.axz.me/*"

[assets]
directory = "./web/dist"
not_found_handling = "single-page-application"

[observability.logs]
enabled = true

